"""
Django settings for identipy_server project.

Generated by 'django-admin startproject' using Django 1.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
import zipfile

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'pv0^x(*qfo_e$#3@f_v_9%@hr3i#+7-y!pjd)p7byzg6bli4q-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1']

DATETIME_FORMAT = 'M j, H:i:s'

# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'identipy_app.apps.IdentipyAppConfig',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'identipy_server.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(os.path.dirname(__file__), '../templates'), ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.media',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'identipy_app.context_processors.menubar',
            ],
        },
    },
]

WSGI_APPLICATION = 'identipy_server.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
#       'ENGINE': 'django.db.backends.mysql',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#       'NAME': 'identipy_server_testing',
        'OPTIONS': {
#           'read_default_file': os.path.join(BASE_DIR, 'identipy_server', 'my.cnf'),
        },
        'TIME_ZONE': 'Europe/Moscow',
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = False

USE_L10N = False

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

MEDIA_ROOT=''
MEDIA_URL='/media/'

STATIC_URL = '/static/'
STATIC_ROOT = ''

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'identipy_app', 'static'),
]

MEDIA_ROOT = ''
MEDIA_URL = '/'

EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = ''
EMAIL_HOST_PASSWORD = ''
EMAIL_SEND_TO = []

NUMBER_OF_PARALLEL_RUNS = 3

# Compression for downloaded ZIP archives.
# ZIP_STORED (no compression) is faster, ZIP_DEFLATED produces smaller files
ZIP_COMPRESSION = zipfile.ZIP_STORED
ALLOW_ZIP64 = True

LOCAL_IMPORT = True
URL_IMPORT = True

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '%(levelname)8s: %(asctime)s %(module)16s %(process)5d %(threadName)12s %(message)s'
            },
        'simple': {
            'format': '%(levelname)s %(message)s'
            },
        },
    'handlers': {
        'server_file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'identipy_server.log'),
            'formatter': 'verbose',
            },
        'identipy_file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'identipy.log'),
            'formatter': 'verbose',
            },
        'mpscore_file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'mp-score.log'),
            'formatter': 'verbose',
            },
        'stream': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            },
        'null': {
            'class': 'logging.NullHandler',
            },
        'ipy_socket': {
            'class': 'logging.handlers.SocketHandler',
            'host': 'localhost',
            'port': 13014,
            },
        'mp_socket': {
            'class': 'logging.handlers.SocketHandler',
            'host': 'localhost',
            'port': 13013,
            },
        },
    'loggers': {
        'django': {
            'handlers': ['stream'],
            'level': 'INFO',
            'propagate': True,
        },
        'identipy_app': {
            'handlers': ['server_file'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'identipy': {
            'handlers': ['ipy_socket'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'MPlib': {
            'handlers': ['mp_socket'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'MPscore': {
            'handlers': ['mp_socket'],
            'level': 'DEBUG',
            'propagate': True,
        },

    },
}

