# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-26 11:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import identipy_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FastaFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('docfile', models.FileField(upload_to=identipy_app.models.upload_to_fasta)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Modification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('label', models.CharField(max_length=30)),
                ('aminoacid', models.CharField(max_length=1)),
                ('mass', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParamsFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('docfile', models.FileField(upload_to=identipy_app.models.upload_to_params)),
                ('type', models.IntegerField(default=3)),
                ('visible', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PepXMLFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('docfile', models.FileField(storage=identipy_app.models.OverwriteStorage(), upload_to=identipy_app.models.upload_to_pepxml)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Protease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('rule', models.CharField(default=b'RK', max_length=300)),
                ('order_val', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RawFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('docfile', models.FileField(upload_to=identipy_app.models.upload_to_raw)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResCSV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('docfile', models.FileField(storage=identipy_app.models.OverwriteStorage(), upload_to=identipy_app.models.upload_to_pepxml)),
                ('ftype', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResImageFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('docfile', models.ImageField(storage=identipy_app.models.OverwriteStorage(), upload_to=identipy_app.models.upload_to_pepxml)),
                ('ftype', models.CharField(default=b'.png', max_length=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SearchGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('groupname', models.CharField(default=b'test', max_length=80)),
                ('status', models.CharField(default=b'No info', max_length=80)),
                ('processpid', models.IntegerField(default=9999)),
                ('fasta', models.ManyToManyField(to='identipy_app.FastaFile')),
                ('parameters', models.ManyToManyField(to='identipy_app.ParamsFile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SearchRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('runname', models.CharField(max_length=80)),
                ('numMSMS', models.BigIntegerField(default=0)),
                ('totalPSMs', models.BigIntegerField(default=0)),
                ('fdr_psms', models.FloatField(default=0.0)),
                ('fdr_type', models.CharField(default=b'-', max_length=80)),
                ('numPSMs', models.BigIntegerField(default=0)),
                ('numPeptides', models.BigIntegerField(default=0)),
                ('numProteins', models.BigIntegerField(default=0)),
                ('union', models.BooleanField(default=False)),
                ('notification', models.BooleanField(default=False)),
                ('csvfiles', models.ManyToManyField(to='identipy_app.ResCSV')),
                ('fasta', models.ManyToManyField(to='identipy_app.FastaFile')),
                ('parameters', models.ManyToManyField(to='identipy_app.ParamsFile')),
                ('pepxmlfiles', models.ManyToManyField(to='identipy_app.PepXMLFile')),
                ('resimagefiles', models.ManyToManyField(to='identipy_app.ResImageFile')),
                ('searchgroup_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identipy_app.SearchGroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpectraFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('docfile', models.FileField(upload_to=identipy_app.models.upload_to_spectra)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='searchrun',
            name='spectra',
            field=models.ManyToManyField(to='identipy_app.SpectraFile'),
        ),
        migrations.AddField(
            model_name='searchrun',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='protease',
            unique_together=set([('name', 'user')]),
        ),
        migrations.AlterUniqueTogether(
            name='modification',
            unique_together=set([('name', 'user', 'aminoacid', 'mass', 'label')]),
        ),
    ]
