# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-29 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identipy_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modification',
            name='aminoacid',
            field=models.CharField(max_length=2),
        ),
    ]
