# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-17 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identipy_app', '0002_auto_20170529_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='pepxmlfile',
            name='filtered',
            field=models.BooleanField(default=False),
        ),
    ]
