# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-21 23:06
from __future__ import unicode_literals

from django.db import migrations, models
from identipy_app.models import SearchRun

def define_runs(apps, schema_editor):
    PepXMLFile = apps.get_model('identipy_app', 'PepXMLFile')
    SearchRun = apps.get_model('identipy_app', 'SearchRun')
    f2r = {}
    for run in SearchRun.objects.all():
        for f in run.pepxmlfiles.all():
            f2r[f] = run
    for pepf in PepXMLFile.objects.all():
        pepf.run = f2r[pepf]
        pepf.save()

class Migration(migrations.Migration):

    dependencies = [
        ('identipy_app', '0003_pepxmlfile_filtered'),
    ]

    operations = [
            migrations.AddField('PepXMLFile', 'run', models.ForeignKey('SearchRun', null=True, on_delete=models.CASCADE), False),
            migrations.RunPython(define_runs),
            migrations.AlterField('PepXMLFile', 'run', models.ForeignKey('SearchRun', on_delete=models.CASCADE), True),
    ]
