# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-21 23:10
from __future__ import unicode_literals

from django.db import migrations, models

def define_runs(apps, schema_editor):
    SearchRun = apps.get_model('identipy_app', 'SearchRun')
    ResCSV = apps.get_model('identipy_app', 'ResCSV')
    f2r = {}
    for run in SearchRun.objects.all():
        for f in run.csvfiles.all():
            f2r[f] = run
    for csv in ResCSV.objects.all():
        csv.run = f2r.get(csv, SearchRun.objects.all().first())
        csv.save()

class Migration(migrations.Migration):

    dependencies = [
        ('identipy_app', '0004_auto_20171222_0206'),
    ]

    operations = [
            migrations.AddField('ResCSV', 'run', models.ForeignKey('SearchRun', null=True), False),
            migrations.RunPython(define_runs),
            migrations.AlterField('ResCSV', 'run', models.ForeignKey('SearchRun'), True),
    ]
