# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-21 23:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

def derive_fdrtype(apps, schema_editor):
    SearchRun = apps.get_model('identipy_app', 'SearchRun')
    SearchGroup = apps.get_model('identipy_app', 'SearchGroup')
    for sg in SearchGroup.objects.all():
        fdr = SearchRun.objects.filter(searchgroup=sg).first().fdr_type
        try:
            sg.fdr_type = {'psm': 'S', 'peptide': 'P', 'protein': 'R'}[fdr]
        except KeyError:
            sg.fdr_type = 'S'
            print('FDR type unspecified, using PSM:', sg.id, sg.groupname)
        sg.save()

class Migration(migrations.Migration):

    dependencies = [
        ('identipy_app', '0006_auto_20171222_0213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchrun',
            old_name='searchgroup_parent',
            new_name='searchgroup',
        ),
        migrations.RemoveField(
            model_name='searchgroup',
            name='processpid',
        ),
        migrations.RemoveField(
            model_name='searchgroup',
            name='status',
        ),
        migrations.RemoveField(
            model_name='searchrun',
            name='csvfiles',
        ),
        migrations.RemoveField(
            model_name='searchrun',
            name='fasta',
        ),
        migrations.AddField(
            model_name='searchgroup',
            name='fdr_type',
            field=models.CharField(choices=[(b'S', b'PSM'), (b'P', b'peptide'), (b'R', b'protein')], default=b'S', max_length=1),
        ),
        migrations.RunPython(derive_fdrtype),
        migrations.RemoveField(
            model_name='searchrun',
            name='fdr_type',
        ),
        migrations.RemoveField(
            model_name='searchrun',
            name='notification',
        ),
        migrations.RemoveField(
            model_name='searchrun',
            name='parameters',
        ),
        migrations.RemoveField(
            model_name='searchrun',
            name='pepxmlfiles',
        ),
        migrations.RemoveField(
            model_name='searchrun',
            name='resimagefiles',
        ),
        migrations.AddField(
            model_name='searchgroup',
            name='notification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='searchrun',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='searchrun',
            name='processpid',
            field=models.IntegerField(blank=True, default=-1),
        ),
        migrations.AddField(
            model_name='searchrun',
            name='status',
            field=models.CharField(choices=[(b'W', b'Waiting'), (b'R', b'Running'), (b'F', b'Finished'), (b'D', b'Dead')], default=b'D', max_length=1),
        ),
        migrations.AlterField(
            model_name='searchgroup',
            name='groupname',
            field=models.CharField(default=b'', max_length=80),
        ),
        migrations.RemoveField(
            model_name='searchgroup',
            name='parameters',
        ),
        migrations.AddField(
            model_name='searchgroup',
            name='parameters',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='identipy_app.ParamsFile'),
        ),
        migrations.RemoveField(
            model_name='searchrun',
            name='spectra',
        ),
        migrations.AddField(
            model_name='searchrun',
            name='spectra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='identipy_app.SpectraFile'),
        ),
    ]
