# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-22 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identipy_app', '0007_auto_20171222_0214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchrun',
            name='fdr_psms',
        ),
        migrations.AddField(
            model_name='searchgroup',
            name='fdr_level',
            field=models.FloatField(default=0.0),
        ),
    ]
