# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-30 14:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identipy_app', '0009_auto_20171222_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchrun',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='searchrun',
            name='user',
        ),
    ]
