# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-05 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identipy_app', '0011_auto_20180102_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='paramsfile',
            name='title',
            field=models.CharField(default=b'', max_length=80),
        ),
    ]
