# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-17 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identipy_app', '0012_paramsfile_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchrun',
            name='status',
            field=models.CharField(choices=[(b'W', b'Waiting'), (b'R', b'Running'), (b'V', b'Validation'), (b'F', b'Finished'), (b'D', b'Dead'), (b'E', b'Error')], default=b'D', max_length=1),
        ),
    ]
