# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-19 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identipy_app', '0014_auto_20190719_0415'),
    ]

    operations = [
        migrations.AddField(
            model_name='resimagefile',
            name='imgtype',
            field=models.CharField(choices=[(b'S', b'PSM'), (b'P', b'peptide'), (b'R', b'protein'), (b'O', b'other')], default=b'O', max_length=1),
        ),
        migrations.AddField(
            model_name='searchrun',
            name='numProteinGroups',
            field=models.BigIntegerField(default=0),
        ),
    ]
