# Generated by Django 3.2.4 on 2021-06-10 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('identipy_app', '0017_auto_20200301_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paramsfile',
            name='title',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='protease',
            name='rule',
            field=models.CharField(default='RK', max_length=300),
        ),
        migrations.AlterField(
            model_name='resimagefile',
            name='ftype',
            field=models.CharField(default='.png', max_length=5),
        ),
        migrations.AlterField(
            model_name='resimagefile',
            name='imgtype',
            field=models.CharField(choices=[('S', 'PSM'), ('P', 'Peptide'), ('R', 'Protein'), ('O', 'Feature')], default='O', max_length=1),
        ),
        migrations.AlterField(
            model_name='searchgroup',
            name='groupname',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='searchgroup',
            name='parameters',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='identipy_app.paramsfile'),
        ),
        migrations.AlterField(
            model_name='searchrun',
            name='spectra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='identipy_app.spectrafile'),
        ),
        migrations.AlterField(
            model_name='searchrun',
            name='status',
            field=models.CharField(choices=[('W', 'Waiting'), ('R', 'Running'), ('V', 'Postsearch processing'), ('F', 'Finished'), ('D', 'Dead'), ('E', 'Error')], default='D', max_length=1),
        ),
    ]
