# Generated by Django 3.2.4 on 2021-06-22 11:10

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('identipy_app', '0018_auto_20210610_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=80)),
                ('send_email_notification', models.BooleanField(default=False)),
                ('use_auto_optimization', models.BooleanField(default=True)),
                ('fdr', models.FloatField(default=1.0, verbose_name='FDR level, %')),
                ('precursor_accuracy_unit', models.CharField(choices=[('P', 'ppm'), ('D', 'Da')], default='P', max_length=1)),
                ('precursor_accuracy_left', models.FloatField(default=10.0)),
                ('precursor_accuracy_right', models.FloatField(default=10.0)),
                ('product_accuracy', models.FloatField(default=0.1, help_text='Product ion accuracy in Th')),
                ('product_minimum_mz', models.FloatField(default=150, verbose_name='product minimum m/z')),
                ('peptide_maximum_length', models.PositiveSmallIntegerField(default=50)),
                ('peptide_minimum_length', models.PositiveSmallIntegerField(default=5)),
                ('peptide_maximum_mass', models.FloatField(default=10000)),
                ('peptide_minimum_mass', models.FloatField(default=300)),
                ('number_of_missed_cleavages', models.PositiveSmallIntegerField(default=2)),
                ('maximum_charge', models.PositiveSmallIntegerField(default=3)),
                ('minimum_charge', models.PositiveSmallIntegerField(default=2)),
                ('precursor_isotope_mass_error', models.PositiveSmallIntegerField(default=0)),
                ('mass_shifts', models.CharField(blank=True, help_text='A set of mass shifts to apply to all peptides for matching. Example: 0, 16.000, 23.000', max_length=80)),
                ('snp', models.BooleanField(default=False, help_text='make SNP changes for ALL peptides')),
                ('protein_cterm_cleavage', models.FloatField(default=17.002735)),
                ('protein_nterm_cleavage', models.FloatField(default=1.007825)),
                ('maximum_variable_mods', models.PositiveSmallIntegerField(default=2)),
                ('add_decoy', models.BooleanField(default=False)),
                ('decoy_prefix', models.CharField(blank=True, default='DECOY_', max_length=20)),
                ('decoy_method', models.CharField(choices=[('R', 'reverse'), ('S', 'shuffle')], default='R', max_length=1)),
                ('minimum_peaks', models.PositiveSmallIntegerField(default=4)),
                ('maximum_peaks', models.PositiveSmallIntegerField(default=50)),
                ('dynamic_range', models.FloatField(default=100.0)),
                ('maximum_fragment_charge', models.PositiveSmallIntegerField(default=0)),
                ('deisotope', models.BooleanField(default=True)),
                ('deisotoping_mass_tolerance', models.FloatField(default=0.3)),
                ('fixed_modifications', models.ManyToManyField(related_name='_identipy_app_searchparameters_fixed_modifications_+', to='identipy_app.Modification')),
            ],
        ),
        migrations.AlterField(
            model_name='protease',
            name='rule',
            field=models.CharField(max_length=80),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('latest_params', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identipy_app.searchparameters')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='searchparameters',
            name='proteases',
            field=models.ManyToManyField(to='identipy_app.Protease'),
        ),
        migrations.AddField(
            model_name='searchparameters',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identipy_app.user'),
        ),
        migrations.AddField(
            model_name='searchparameters',
            name='variable_modifications',
            field=models.ManyToManyField(related_name='_identipy_app_searchparameters_variable_modifications_+', to='identipy_app.Modification'),
        ),

    ]
