# Generated by Django 3.2.4 on 2021-06-22 11:10

from django.db import migrations
from django.forms import model_to_dict
import django.contrib.auth.models

def recreate_user(apps, schema_editor):
    User = apps.get_model('identipy_app', 'User')
    SearchParameters = apps.get_model('identipy_app', 'SearchParameters')
    for obj in django.contrib.auth.models.User.objects.all():
        d = model_to_dict(obj)
        del d['groups']
        del d['user_permissions']
        u = User.objects.create(**d)
        u.save()
        u.latest_params = SearchParameters.objects.create(user=u)
        u.save()


def undo_recreate_user(apps, schema_editor):
    SearchParameters = apps.get_model('identipy_app', 'SearchParameters')
    SearchParameters.objects.all().delete()

    User = apps.get_model('identipy_app', 'User')
    User.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('identipy_app', '0019_auto_20210622_1410'),
    ]

    operations = [
        migrations.RunPython(recreate_user, undo_recreate_user)
    ]
