# Generated by Django 3.2.4 on 2021-06-22 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('identipy_app', '0020_auto_20210622_1410'),
    ]

    operations = [

        migrations.AlterField(
            model_name='fastafile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identipy_app.user'),
        ),
        migrations.AlterField(
            model_name='modification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identipy_app.user'),
        ),
        migrations.AlterField(
            model_name='paramsfile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identipy_app.user'),
        ),
        migrations.AlterField(
            model_name='pepxmlfile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identipy_app.user'),
        ),
        migrations.AlterField(
            model_name='protease',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identipy_app.user'),
        ),
        migrations.AlterField(
            model_name='rawfile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identipy_app.user'),
        ),
        migrations.AlterField(
            model_name='rescsv',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identipy_app.user'),
        ),
        migrations.AlterField(
            model_name='resimagefile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identipy_app.user'),
        ),
        migrations.AlterField(
            model_name='searchgroup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identipy_app.user'),
        ),
        migrations.AlterField(
            model_name='spectrafile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identipy_app.user'),
        ),
    ]
