# Generated by Django 3.2.4 on 2021-10-15 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identipy_app', '0021_auto_20210622_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchparameters',
            name='fixed_modifications',
            field=models.ManyToManyField(blank=True, related_name='_identipy_app_searchparameters_fixed_modifications_+', to='identipy_app.Modification'),
        ),
        migrations.AlterField(
            model_name='searchparameters',
            name='variable_modifications',
            field=models.ManyToManyField(blank=True, related_name='_identipy_app_searchparameters_variable_modifications_+', to='identipy_app.Modification'),
        ),
    ]
