# Generated by Django 4.0.4 on 2022-05-25 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('identipy_app', '0022_auto_20211015_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pepxmlfile',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identipy_app.searchrun'),
        ),
        migrations.AlterField(
            model_name='rescsv',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identipy_app.searchrun'),
        ),
        migrations.AlterField(
            model_name='resimagefile',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identipy_app.searchrun'),
        ),
        migrations.AlterField(
            model_name='searchparameters',
            name='fixed_modifications',
            field=models.ManyToManyField(blank=True, related_name='+', to='identipy_app.modification'),
        ),
        migrations.AlterField(
            model_name='searchparameters',
            name='variable_modifications',
            field=models.ManyToManyField(blank=True, related_name='+', to='identipy_app.modification'),
        ),
    ]
