# Generated by Django 4.0.4 on 2022-06-29 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identipy_app', '0025_remove_searchgroup_parameters'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchgroup',
            old_name='params_obj',
            new_name='parameters',
        ),
    ]
