# Generated by Django 4.0.4 on 2022-07-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identipy_app', '0026_rename_params_obj_searchgroup_parameters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchparameters',
            name='snp',
            field=models.SmallIntegerField(default=0, help_text='make SNP changes for ALL peptides'),
        ),
    ]
