# Generated by Django 4.0.4 on 2022-07-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identipy_app', '0027_alter_searchparameters_snp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchparameters',
            name='mass_shifts',
            field=models.CharField(default='0', help_text='A set of mass shifts to apply to all peptides for matching. Example: 0, 16.000, 23.000', max_length=80),
        ),
    ]
