# Generated by Django 4.0.4 on 2022-07-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identipy_app', '0028_alter_searchparameters_mass_shifts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchparameters',
            name='snp',
            field=models.PositiveSmallIntegerField(default=0, help_text='make SNP changes for ALL peptides'),
        ),
    ]
